#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE,POLYGON, SELECT};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, SEND_TO_BACK,SEND_TO_FRONT,SIZE_INCREASE,SIZE_DECREASE, CLEAR};

#endif